// audit-actions.ts
export enum AuditAction {
  LOGIN = 'LOGIN',
  SET_PASSWORD = 'SET_PASSWORD',
  UPLOAD_MEETINGS = 'UPLOAD_MEETINGS',
  UPLOAD_PIPELINE = 'UPLOAD_PIPELINE',
  CREATE_PIPELINE_OPPORTUNITY = 'CREATE_PIPELINE_OPPORTUNITY',
  UPDATE_PIPELINE_OPPORTUNITY = 'UPDATE_PIPELINE_OPPORTUNITY',
  DELETE_OPPORTUNITY = 'DELETE_PIPELINE_OPPORTUNITY',
  DELETE_MEETING = 'DELETE_MEETING',
}
